;  interstitials are disabled in M.o.S II
; the interstitial types for interstitialActive
INTERSTITIAL_LIVELOST		= $01
INTERSTITIAL_FADEOUT		= $02
INTERSTITIAL_FADEIN			= $03
INTERSTITIAL_FADEINPLAYER	= $04
INTERSTITIAL_FAIRIESGODOWN	= $05
INTERSTITIAL_FAIRIESGOUP	= $06
INTERSTITIAL_LEVELCOMPLETED	= $07
INTERSTITIALFLAG_LEVELCOMPLETE = $01
INTERSTITIALFLAG_GAMEOVER	   = $02