LAYERCOUNT = 16
LAYER0
	dc.b 1; is layer currently on?
	dc.b 11,58 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 12,58 ; X AND Y
	dc.b 0,113 ; BEFORE AND LAYER
	dc.b 13,58 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 14,58 ; X AND Y
	dc.b 0,113 ; BEFORE AND LAYER
	dc.b 15,58 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 16,58 ; X AND Y
	dc.b 0,113 ; BEFORE AND LAYER
	dc.b 13,59 ; X AND Y
	dc.b 114,129 ; BEFORE AND LAYER
	dc.b 11,60 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 12,60 ; X AND Y
	dc.b 0,113 ; BEFORE AND LAYER
	dc.b 13,60 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 14,60 ; X AND Y
	dc.b 0,113 ; BEFORE AND LAYER
	dc.b 15,60 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 16,60 ; X AND Y
	dc.b 0,113 ; BEFORE AND LAYER
	dc.b 12,61 ; X AND Y
	dc.b 0,134 ; BEFORE AND LAYER
	dc.b 13,61 ; X AND Y
	dc.b 0,135 ; BEFORE AND LAYER
	dc.b 14,61 ; X AND Y
	dc.b 0,136 ; BEFORE AND LAYER
	dc.b 15,61 ; X AND Y
	dc.b 0,137 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER1
	dc.b 0; is layer currently on?
	dc.b 17,39 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 15,41 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 17,42 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 15,44 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 17,46 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER2
	dc.b 1; is layer currently on?
	dc.b 15,38 ; X AND Y
	dc.b 0,70 ; BEFORE AND LAYER
	dc.b 16,38 ; X AND Y
	dc.b 0,73 ; BEFORE AND LAYER
	dc.b 17,38 ; X AND Y
	dc.b 0,75 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 1; is layer currently on?
	dc.b 16,23 ; X AND Y
	dc.b 0,70 ; BEFORE AND LAYER
	dc.b 17,23 ; X AND Y
	dc.b 0,119 ; BEFORE AND LAYER
	dc.b 18,23 ; X AND Y
	dc.b 0,75 ; BEFORE AND LAYER
	dc.b 16,24 ; X AND Y
	dc.b 0,147 ; BEFORE AND LAYER
	dc.b 17,24 ; X AND Y
	dc.b 0,119 ; BEFORE AND LAYER
	dc.b 17,25 ; X AND Y
	dc.b 0,119 ; BEFORE AND LAYER
	dc.b 18,25 ; X AND Y
	dc.b 0,21 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 1; is layer currently on?
	dc.b 5,4 ; X AND Y
	dc.b 0,120 ; BEFORE AND LAYER
	dc.b 4,5 ; X AND Y
	dc.b 149,119 ; BEFORE AND LAYER
	dc.b 5,5 ; X AND Y
	dc.b 0,128 ; BEFORE AND LAYER
	dc.b 6,5 ; X AND Y
	dc.b 0,23 ; BEFORE AND LAYER
	dc.b 4,6 ; X AND Y
	dc.b 120,121 ; BEFORE AND LAYER
	dc.b 5,6 ; X AND Y
	dc.b 0,116 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER5
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER6
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER7
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER8
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
