LAYERCOUNT = 16
LAYER0
	dc.b 1; is layer currently on?
	dc.b 8,53 ; X AND Y
	dc.b 85,2 ; BEFORE AND LAYER
	dc.b 8,54 ; X AND Y
	dc.b 0,32 ; BEFORE AND LAYER
	dc.b 8,55 ; X AND Y
	dc.b 0,48 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER1
	dc.b 1; is layer currently on?
	dc.b 7,53 ; X AND Y
	dc.b 85,32 ; BEFORE AND LAYER
	dc.b 7,54 ; X AND Y
	dc.b 0,32 ; BEFORE AND LAYER
	dc.b 7,55 ; X AND Y
	dc.b 0,48 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER2
	dc.b 1; is layer currently on?
	dc.b 21,48 ; X AND Y
	dc.b 18,49 ; BEFORE AND LAYER
	dc.b 22,48 ; X AND Y
	dc.b 19,50 ; BEFORE AND LAYER
	dc.b 23,48 ; X AND Y
	dc.b 19,18 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 0; is layer currently on?
	dc.b 18,41 ; X AND Y
	dc.b 0,9 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 1; is layer currently on?
	dc.b 9,33 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 10,33 ; X AND Y
	dc.b 0,49 ; BEFORE AND LAYER
	dc.b 11,33 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b 12,33 ; X AND Y
	dc.b 0,50 ; BEFORE AND LAYER
	dc.b 10,34 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 11,34 ; X AND Y
	dc.b 0,32 ; BEFORE AND LAYER
	dc.b 8,35 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 9,35 ; X AND Y
	dc.b 0,49 ; BEFORE AND LAYER
	dc.b 10,35 ; X AND Y
	dc.b 0,34 ; BEFORE AND LAYER
	dc.b 11,35 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b 9,36 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 10,36 ; X AND Y
	dc.b 0,16 ; BEFORE AND LAYER
	dc.b 10,37 ; X AND Y
	dc.b 0,48 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER5
	dc.b 1; is layer currently on?
	dc.b 20,29 ; X AND Y
	dc.b 0,69 ; BEFORE AND LAYER
	dc.b 21,29 ; X AND Y
	dc.b 0,70 ; BEFORE AND LAYER
	dc.b 22,29 ; X AND Y
	dc.b 0,69 ; BEFORE AND LAYER
	dc.b 23,29 ; X AND Y
	dc.b 0,70 ; BEFORE AND LAYER
	dc.b 20,30 ; X AND Y
	dc.b 0,85 ; BEFORE AND LAYER
	dc.b 21,30 ; X AND Y
	dc.b 0,32 ; BEFORE AND LAYER
	dc.b 22,30 ; X AND Y
	dc.b 0,86 ; BEFORE AND LAYER
	dc.b 23,30 ; X AND Y
	dc.b 0,84 ; BEFORE AND LAYER
	dc.b 21,31 ; X AND Y
	dc.b 0,2 ; BEFORE AND LAYER
	dc.b 22,31 ; X AND Y
	dc.b 0,44 ; BEFORE AND LAYER
	dc.b 21,32 ; X AND Y
	dc.b 70,32 ; BEFORE AND LAYER
	dc.b 22,32 ; X AND Y
	dc.b 0,45 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER6
	dc.b 1; is layer currently on?
	dc.b 31,6 ; X AND Y
	dc.b 49,69 ; BEFORE AND LAYER
	dc.b 27,7 ; X AND Y
	dc.b 0,49 ; BEFORE AND LAYER
	dc.b 28,7 ; X AND Y
	dc.b 0,34 ; BEFORE AND LAYER
	dc.b 29,7 ; X AND Y
	dc.b 0,34 ; BEFORE AND LAYER
	dc.b 30,7 ; X AND Y
	dc.b 0,34 ; BEFORE AND LAYER
	dc.b 31,7 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b 32,7 ; X AND Y
	dc.b 0,86 ; BEFORE AND LAYER
	dc.b 31,8 ; X AND Y
	dc.b 0,8 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER7
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER8
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
