PCOLOR0 = 0
PCOLOR1 = 65
PCOLOR2 = 113
PCOLOR3 = 97
PCOLOR0iter
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
	dc.b 0
PCOLOR1iter
	dc.b 0
	dc.b 1
	dc.b 1
	dc.b 17
	dc.b 17
	dc.b 33
	dc.b 33
	dc.b 49
	dc.b 65
PCOLOR2iter
	dc.b 0
	dc.b 1
	dc.b 17
	dc.b 33
	dc.b 49
	dc.b 65
	dc.b 81
	dc.b 97
	dc.b 113
PCOLOR3iter
	dc.b 8
	dc.b 9
	dc.b 9
	dc.b 25
	dc.b 41
	dc.b 57
	dc.b 73
	dc.b 89
	dc.b 105
