LAYERCOUNT = 16
LAYER0
	dc.b 0; is layer currently on?
	dc.b 13,1 ; X AND Y
	dc.b 0,157 ; BEFORE AND LAYER
	dc.b 13,2 ; X AND Y
	dc.b 0,41 ; BEFORE AND LAYER
	dc.b 14,3 ; X AND Y
	dc.b 0,41 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
	dc.b $fe ; itemattached
	dc.b 53,5 ; itemPosX, itemPosY
LAYER1
	dc.b 1; is layer currently on?
	dc.b 38,7 ; X AND Y
	dc.b 2,3 ; BEFORE AND LAYER
	dc.b 39,7 ; X AND Y
	dc.b 0,8 ; BEFORE AND LAYER
	dc.b 38,8 ; X AND Y
	dc.b 2,69 ; BEFORE AND LAYER
	dc.b 39,8 ; X AND Y
	dc.b 9,70 ; BEFORE AND LAYER
	dc.b 38,9 ; X AND Y
	dc.b 2,69 ; BEFORE AND LAYER
	dc.b 39,9 ; X AND Y
	dc.b 25,70 ; BEFORE AND LAYER
	dc.b 38,10 ; X AND Y
	dc.b 2,69 ; BEFORE AND LAYER
	dc.b 39,10 ; X AND Y
	dc.b 0,70 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER2
	dc.b 0; is layer currently on?
	dc.b 29,3 ; X AND Y
	dc.b 0,41 ; BEFORE AND LAYER
	dc.b 31,5 ; X AND Y
	dc.b 0,41 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 1; is layer currently on?
	dc.b 2,13 ; X AND Y
	dc.b 0,10 ; BEFORE AND LAYER
	dc.b 3,13 ; X AND Y
	dc.b 0,8 ; BEFORE AND LAYER
	dc.b 2,14 ; X AND Y
	dc.b 84,93 ; BEFORE AND LAYER
	dc.b 3,14 ; X AND Y
	dc.b 83,94 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 1; is layer currently on?
	dc.b 39,23 ; X AND Y
	dc.b 0,32 ; BEFORE AND LAYER
	dc.b 38,24 ; X AND Y
	dc.b 15,14 ; BEFORE AND LAYER
	dc.b 39,24 ; X AND Y
	dc.b 0,14 ; BEFORE AND LAYER
	dc.b 38,25 ; X AND Y
	dc.b 68,66 ; BEFORE AND LAYER
	dc.b 39,25 ; X AND Y
	dc.b 0,66 ; BEFORE AND LAYER
	dc.b 38,26 ; X AND Y
	dc.b 0,67 ; BEFORE AND LAYER
	dc.b 39,26 ; X AND Y
	dc.b 0,66 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER5
	dc.b 0; is layer currently on?
	dc.b 13,16 ; X AND Y
	dc.b 34,45 ; BEFORE AND LAYER
	dc.b 10,17 ; X AND Y
	dc.b 0,30 ; BEFORE AND LAYER
	dc.b 11,17 ; X AND Y
	dc.b 0,30 ; BEFORE AND LAYER
	dc.b 13,17 ; X AND Y
	dc.b 0,30 ; BEFORE AND LAYER
	dc.b 14,17 ; X AND Y
	dc.b 0,46 ; BEFORE AND LAYER
	dc.b 11,18 ; X AND Y
	dc.b 0,61 ; BEFORE AND LAYER
	dc.b 12,18 ; X AND Y
	dc.b 0,156 ; BEFORE AND LAYER
	dc.b 13,18 ; X AND Y
	dc.b 0,16 ; BEFORE AND LAYER
	dc.b 11,19 ; X AND Y
	dc.b 0,41 ; BEFORE AND LAYER
	dc.b 12,19 ; X AND Y
	dc.b 0,25 ; BEFORE AND LAYER
	dc.b 13,19 ; X AND Y
	dc.b 0,57 ; BEFORE AND LAYER
	dc.b 13,20 ; X AND Y
	dc.b 0,30 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
	dc.b $fe ; itemattached
	dc.b 49,73 ; itemPosX, itemPosY
LAYER6
	dc.b 1; is layer currently on?
	dc.b 38,47 ; X AND Y
	dc.b 0,32 ; BEFORE AND LAYER
	dc.b 39,47 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b 39,48 ; X AND Y
	dc.b 0,14 ; BEFORE AND LAYER
	dc.b 39,49 ; X AND Y
	dc.b 0,14 ; BEFORE AND LAYER
	dc.b 39,50 ; X AND Y
	dc.b 0,14 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER7
	dc.b 1; is layer currently on?
	dc.b 33,42 ; X AND Y
	dc.b 0,18 ; BEFORE AND LAYER
	dc.b 33,43 ; X AND Y
	dc.b 0,67 ; BEFORE AND LAYER
	dc.b 34,43 ; X AND Y
	dc.b 17,89 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER8
	dc.b 1; is layer currently on?
	dc.b 29,52 ; X AND Y
	dc.b 64,82 ; BEFORE AND LAYER
	dc.b 30,52 ; X AND Y
	dc.b 16,66 ; BEFORE AND LAYER
	dc.b 31,52 ; X AND Y
	dc.b 17,84 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER9
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
