
CURRENTSCREENS
	dc.b 0
	dc.b 1
	dc.b 2
	dc.b 3
	dc.b 4
	dc.b 5
	dc.b 6
	dc.b 7
	dc.b 8
	dc.b 9
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
	dc.b $00 ; empty
