LAYERCOUNT = 16
LAYER0
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER1
	dc.b 0; is layer currently on?
	dc.b 36,60 ; X AND Y
	dc.b 0,86 ; BEFORE AND LAYER
	dc.b 36,61 ; X AND Y
	dc.b 0,38 ; BEFORE AND LAYER
	dc.b 37,61 ; X AND Y
	dc.b 0,39 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER2
	dc.b 1; is layer currently on?
	dc.b 31,29 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b 32,29 ; X AND Y
	dc.b 0,22 ; BEFORE AND LAYER
	dc.b 33,29 ; X AND Y
	dc.b 0,34 ; BEFORE AND LAYER
	dc.b 34,29 ; X AND Y
	dc.b 38,37 ; BEFORE AND LAYER
	dc.b 35,29 ; X AND Y
	dc.b 57,36 ; BEFORE AND LAYER
	dc.b 36,29 ; X AND Y
	dc.b 0,19 ; BEFORE AND LAYER
	dc.b 37,29 ; X AND Y
	dc.b 0,23 ; BEFORE AND LAYER
	dc.b 38,29 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 1; is layer currently on?
	dc.b 34,22 ; X AND Y
	dc.b 13,12 ; BEFORE AND LAYER
	dc.b 35,22 ; X AND Y
	dc.b 0,12 ; BEFORE AND LAYER
	dc.b 36,22 ; X AND Y
	dc.b 0,12 ; BEFORE AND LAYER
	dc.b 37,22 ; X AND Y
	dc.b 11,12 ; BEFORE AND LAYER
	dc.b 33,23 ; X AND Y
	dc.b 29,28 ; BEFORE AND LAYER
	dc.b 34,23 ; X AND Y
	dc.b 0,43 ; BEFORE AND LAYER
	dc.b 37,23 ; X AND Y
	dc.b 0,44 ; BEFORE AND LAYER
	dc.b 38,23 ; X AND Y
	dc.b 27,28 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 0; is layer currently on?
	dc.b 39,33 ; X AND Y
	dc.b 0,157 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
	dc.b $fe ; itemattached
	dc.b 157,133 ; itemPosX, itemPosY
LAYER5
	dc.b 1; is layer currently on?
	dc.b 29,9 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 30,9 ; X AND Y
	dc.b 0,19 ; BEFORE AND LAYER
	dc.b 28,10 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 29,10 ; X AND Y
	dc.b 0,18 ; BEFORE AND LAYER
	dc.b 30,10 ; X AND Y
	dc.b 0,37 ; BEFORE AND LAYER
	dc.b 26,11 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b 27,11 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 28,11 ; X AND Y
	dc.b 0,50 ; BEFORE AND LAYER
	dc.b 29,11 ; X AND Y
	dc.b 0,25 ; BEFORE AND LAYER
	dc.b 30,11 ; X AND Y
	dc.b 0,10 ; BEFORE AND LAYER
	dc.b 31,11 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b 27,12 ; X AND Y
	dc.b 0,36 ; BEFORE AND LAYER
	dc.b 28,12 ; X AND Y
	dc.b 0,50 ; BEFORE AND LAYER
	dc.b 29,12 ; X AND Y
	dc.b 0,37 ; BEFORE AND LAYER
	dc.b 30,12 ; X AND Y
	dc.b 0,38 ; BEFORE AND LAYER
	dc.b 28,13 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b 27,14 ; X AND Y
	dc.b 91,9 ; BEFORE AND LAYER
	dc.b 28,14 ; X AND Y
	dc.b 0,50 ; BEFORE AND LAYER
	dc.b 29,14 ; X AND Y
	dc.b 0,10 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER6
	dc.b 1; is layer currently on?
	dc.b 27,0 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b 28,0 ; X AND Y
	dc.b 0,22 ; BEFORE AND LAYER
	dc.b 29,0 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 30,0 ; X AND Y
	dc.b 0,23 ; BEFORE AND LAYER
	dc.b 31,0 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b 29,1 ; X AND Y
	dc.b 0,36 ; BEFORE AND LAYER
	dc.b 30,1 ; X AND Y
	dc.b 0,21 ; BEFORE AND LAYER
	dc.b 31,1 ; X AND Y
	dc.b 0,24 ; BEFORE AND LAYER
	dc.b 29,2 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 30,2 ; X AND Y
	dc.b 0,10 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER7
	dc.b 1; is layer currently on?
	dc.b 32,0 ; X AND Y
	dc.b 0,66 ; BEFORE AND LAYER
	dc.b 33,0 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 34,0 ; X AND Y
	dc.b 0,23 ; BEFORE AND LAYER
	dc.b 32,1 ; X AND Y
	dc.b 0,38 ; BEFORE AND LAYER
	dc.b 33,1 ; X AND Y
	dc.b 0,36 ; BEFORE AND LAYER
	dc.b 34,1 ; X AND Y
	dc.b 0,21 ; BEFORE AND LAYER
	dc.b 32,2 ; X AND Y
	dc.b 0,38 ; BEFORE AND LAYER
	dc.b 33,2 ; X AND Y
	dc.b 0,57 ; BEFORE AND LAYER
	dc.b 34,2 ; X AND Y
	dc.b 0,36 ; BEFORE AND LAYER
	dc.b 35,2 ; X AND Y
	dc.b 0,21 ; BEFORE AND LAYER
	dc.b 36,2 ; X AND Y
	dc.b 0,23 ; BEFORE AND LAYER
	dc.b 34,3 ; X AND Y
	dc.b 9,20 ; BEFORE AND LAYER
	dc.b 35,3 ; X AND Y
	dc.b 25,18 ; BEFORE AND LAYER
	dc.b 36,3 ; X AND Y
	dc.b 23,37 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER8
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
