LAYERCOUNT = 16
LAYER0
	dc.b 1; is layer currently on?
	dc.b 34,32 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 36,32 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 34,33 ; X AND Y
	dc.b 0,49 ; BEFORE AND LAYER
	dc.b 35,33 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b 36,33 ; X AND Y
	dc.b 0,49 ; BEFORE AND LAYER
	dc.b 37,33 ; X AND Y
	dc.b 0,40 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER1
	dc.b 0; is layer currently on?
	dc.b 27,30 ; X AND Y
	dc.b 0,157 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
	dc.b $fe ; itemattached
	dc.b 109,121 ; itemPosX, itemPosY
LAYER2
	dc.b 0; is layer currently on?
	dc.b 5,20 ; X AND Y
	dc.b 0,42 ; BEFORE AND LAYER
	dc.b 7,21 ; X AND Y
	dc.b 0,42 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 1; is layer currently on?
	dc.b 11,11 ; X AND Y
	dc.b 0,26 ; BEFORE AND LAYER
	dc.b 11,12 ; X AND Y
	dc.b 0,53 ; BEFORE AND LAYER
	dc.b 12,12 ; X AND Y
	dc.b 0,39 ; BEFORE AND LAYER
	dc.b 12,13 ; X AND Y
	dc.b 0,55 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 0; is layer currently on?
	dc.b 4,45 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER5
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER6
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER7
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER8
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
