LAYERCOUNT = 16
LAYER0
	dc.b 0; is layer currently on?
	dc.b 6,54 ; X AND Y
	dc.b 0,157 ; BEFORE AND LAYER
	dc.b 6,55 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b 9,55 ; X AND Y
	dc.b 0,5 ; BEFORE AND LAYER
	dc.b 12,55 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 8,56 ; X AND Y
	dc.b 0,64 ; BEFORE AND LAYER
	dc.b 9,56 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b 10,56 ; X AND Y
	dc.b 0,80 ; BEFORE AND LAYER
	dc.b 11,56 ; X AND Y
	dc.b 0,81 ; BEFORE AND LAYER
	dc.b 12,56 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b 13,56 ; X AND Y
	dc.b 0,81 ; BEFORE AND LAYER
	dc.b 13,57 ; X AND Y
	dc.b 0,4 ; BEFORE AND LAYER
	dc.b 12,58 ; X AND Y
	dc.b 0,65 ; BEFORE AND LAYER
	dc.b 13,58 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b 14,58 ; X AND Y
	dc.b 0,80 ; BEFORE AND LAYER
	dc.b 14,60 ; X AND Y
	dc.b 0,64 ; BEFORE AND LAYER
	dc.b 15,60 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b 16,60 ; X AND Y
	dc.b 0,81 ; BEFORE AND LAYER
	dc.b 12,61 ; X AND Y
	dc.b 0,66 ; BEFORE AND LAYER
	dc.b 13,61 ; X AND Y
	dc.b 0,13 ; BEFORE AND LAYER
	dc.b 14,61 ; X AND Y
	dc.b 0,82 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
	dc.b $fe ; itemattached
	dc.b 25,217 ; itemPosX, itemPosY
LAYER1
	dc.b 1; is layer currently on?
	dc.b 28,55 ; X AND Y
	dc.b 0,28 ; BEFORE AND LAYER
	dc.b 29,55 ; X AND Y
	dc.b 0,31 ; BEFORE AND LAYER
	dc.b 28,56 ; X AND Y
	dc.b 0,16 ; BEFORE AND LAYER
	dc.b 28,57 ; X AND Y
	dc.b 0,16 ; BEFORE AND LAYER
	dc.b 28,58 ; X AND Y
	dc.b 99,16 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER2
	dc.b 1; is layer currently on?
	dc.b 1,41 ; X AND Y
	dc.b 0,99 ; BEFORE AND LAYER
	dc.b 0,42 ; X AND Y
	dc.b 13,90 ; BEFORE AND LAYER
	dc.b 1,42 ; X AND Y
	dc.b 0,90 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 1; is layer currently on?
	dc.b 6,37 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 5,38 ; X AND Y
	dc.b 0,28 ; BEFORE AND LAYER
	dc.b 6,38 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 5,39 ; X AND Y
	dc.b 0,16 ; BEFORE AND LAYER
	dc.b 6,39 ; X AND Y
	dc.b 0,114 ; BEFORE AND LAYER
	dc.b 5,40 ; X AND Y
	dc.b 0,16 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 1; is layer currently on?
	dc.b 24,31 ; X AND Y
	dc.b 0,20 ; BEFORE AND LAYER
	dc.b 25,31 ; X AND Y
	dc.b 0,19 ; BEFORE AND LAYER
	dc.b 25,32 ; X AND Y
	dc.b 0,115 ; BEFORE AND LAYER
	dc.b 26,32 ; X AND Y
	dc.b 119,117 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER5
	dc.b 1; is layer currently on?
	dc.b 1,6 ; X AND Y
	dc.b 0,89 ; BEFORE AND LAYER
	dc.b 2,6 ; X AND Y
	dc.b 0,90 ; BEFORE AND LAYER
	dc.b 3,6 ; X AND Y
	dc.b 0,89 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER6
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER7
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER8
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
