LAYERCOUNT = 16
LAYER0
	dc.b 1; is layer currently on?
	dc.b 31,59 ; X AND Y
	dc.b 2,3 ; BEFORE AND LAYER
	dc.b 32,59 ; X AND Y
	dc.b 37,3 ; BEFORE AND LAYER
	dc.b 33,59 ; X AND Y
	dc.b 37,3 ; BEFORE AND LAYER
	dc.b 34,59 ; X AND Y
	dc.b 1,3 ; BEFORE AND LAYER
	dc.b 31,60 ; X AND Y
	dc.b 2,3 ; BEFORE AND LAYER
	dc.b 32,60 ; X AND Y
	dc.b 53,3 ; BEFORE AND LAYER
	dc.b 33,60 ; X AND Y
	dc.b 21,3 ; BEFORE AND LAYER
	dc.b 34,60 ; X AND Y
	dc.b 1,3 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER1
	dc.b 0; is layer currently on?
	dc.b 2,49 ; X AND Y
	dc.b 19,3 ; BEFORE AND LAYER
	dc.b 3,49 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 4,49 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 5,49 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 6,49 ; X AND Y
	dc.b 2,3 ; BEFORE AND LAYER
	dc.b 2,50 ; X AND Y
	dc.b 2,3 ; BEFORE AND LAYER
	dc.b 3,50 ; X AND Y
	dc.b 16,3 ; BEFORE AND LAYER
	dc.b 4,50 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 5,50 ; X AND Y
	dc.b 68,3 ; BEFORE AND LAYER
	dc.b 6,50 ; X AND Y
	dc.b 1,3 ; BEFORE AND LAYER
	dc.b 2,51 ; X AND Y
	dc.b 2,3 ; BEFORE AND LAYER
	dc.b 3,51 ; X AND Y
	dc.b 67,3 ; BEFORE AND LAYER
	dc.b 4,51 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 5,51 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 6,51 ; X AND Y
	dc.b 1,3 ; BEFORE AND LAYER
	dc.b 3,52 ; X AND Y
	dc.b 0,34 ; BEFORE AND LAYER
	dc.b 4,52 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 5,52 ; X AND Y
	dc.b 16,35 ; BEFORE AND LAYER
	dc.b 26,56 ; X AND Y
	dc.b 0,157 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
	dc.b $fe ; itemattached
	dc.b 105,225 ; itemPosX, itemPosY
LAYER2
	dc.b 1; is layer currently on?
	dc.b 24,37 ; X AND Y
	dc.b 51,3 ; BEFORE AND LAYER
	dc.b 25,37 ; X AND Y
	dc.b 88,3 ; BEFORE AND LAYER
	dc.b 26,37 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b 27,37 ; X AND Y
	dc.b 90,3 ; BEFORE AND LAYER
	dc.b 28,37 ; X AND Y
	dc.b 69,3 ; BEFORE AND LAYER
	dc.b 24,38 ; X AND Y
	dc.b 51,3 ; BEFORE AND LAYER
	dc.b 25,38 ; X AND Y
	dc.b 87,3 ; BEFORE AND LAYER
	dc.b 26,38 ; X AND Y
	dc.b 86,3 ; BEFORE AND LAYER
	dc.b 27,38 ; X AND Y
	dc.b 16,3 ; BEFORE AND LAYER
	dc.b 28,38 ; X AND Y
	dc.b 69,3 ; BEFORE AND LAYER
	dc.b 24,39 ; X AND Y
	dc.b 51,3 ; BEFORE AND LAYER
	dc.b 25,39 ; X AND Y
	dc.b 88,3 ; BEFORE AND LAYER
	dc.b 26,39 ; X AND Y
	dc.b 89,3 ; BEFORE AND LAYER
	dc.b 27,39 ; X AND Y
	dc.b 90,3 ; BEFORE AND LAYER
	dc.b 28,39 ; X AND Y
	dc.b 69,3 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER3
	dc.b 1; is layer currently on?
	dc.b 29,32 ; X AND Y
	dc.b 5,3 ; BEFORE AND LAYER
	dc.b 30,32 ; X AND Y
	dc.b 6,3 ; BEFORE AND LAYER
	dc.b 30,33 ; X AND Y
	dc.b 38,3 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER4
	dc.b 1; is layer currently on?
	dc.b 8,18 ; X AND Y
	dc.b 0,18 ; BEFORE AND LAYER
	dc.b 9,18 ; X AND Y
	dc.b 0,19 ; BEFORE AND LAYER
	dc.b 7,19 ; X AND Y
	dc.b 44,1 ; BEFORE AND LAYER
	dc.b 8,19 ; X AND Y
	dc.b 48,3 ; BEFORE AND LAYER
	dc.b 9,19 ; X AND Y
	dc.b 0,35 ; BEFORE AND LAYER
	dc.b 8,20 ; X AND Y
	dc.b 64,35 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER5
	dc.b 0; is layer currently on?
	dc.b 7,46 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b 11,46 ; X AND Y
	dc.b 0,33 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER6
	dc.b 0; is layer currently on?
	dc.b 25,6 ; X AND Y
	dc.b 67,3 ; BEFORE AND LAYER
	dc.b 26,6 ; X AND Y
	dc.b 68,3 ; BEFORE AND LAYER
	dc.b 25,7 ; X AND Y
	dc.b 50,3 ; BEFORE AND LAYER
	dc.b 26,7 ; X AND Y
	dc.b 0,3 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER7
	dc.b 0; is layer currently on?
	dc.b 8,7 ; X AND Y
	dc.b 48,1 ; BEFORE AND LAYER
	dc.b 9,7 ; X AND Y
	dc.b 50,3 ; BEFORE AND LAYER
	dc.b 10,7 ; X AND Y
	dc.b 49,2 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER8
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 1; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
