LAYERCOUNT = 16
LAYER0
	dc.b 1; is layer currently on?
	dc.b 35,30 ; X AND Y
	dc.b 1,69 ; BEFORE AND LAYER
	dc.b 34,31 ; X AND Y
	dc.b 0,69 ; BEFORE AND LAYER
	dc.b 35,31 ; X AND Y
	dc.b 29,67 ; BEFORE AND LAYER
	dc.b 35,32 ; X AND Y
	dc.b 0,68 ; BEFORE AND LAYER
	dc.b 36,32 ; X AND Y
	dc.b 3,86 ; BEFORE AND LAYER
	dc.b 34,33 ; X AND Y
	dc.b 0,86 ; BEFORE AND LAYER
	dc.b 35,33 ; X AND Y
	dc.b 0,67 ; BEFORE AND LAYER
	dc.b 36,33 ; X AND Y
	dc.b 29,68 ; BEFORE AND LAYER
	dc.b 37,33 ; X AND Y
	dc.b 0,67 ; BEFORE AND LAYER
	dc.b 36,34 ; X AND Y
	dc.b 1,68 ; BEFORE AND LAYER
	dc.b $ff ; endLayer
LAYER1
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER2
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER3
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER4
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER5
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER6
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER7
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER8
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER9
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER10
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER11
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER12
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER13
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER14
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
LAYER15
	dc.b 0; is layer currently on?
	dc.b $ff ; endLayer
